package day11_0801;

/*
 异常的原则：
 	1.功能内部有异常throw抛出，功能上一定要throws声明。
 	2.
 */

class Demo2{
	int div(int a,int b) throws Exception{
		if(b==0)
			throw new ArithmeticException("被0除，错误");
		return a/b;
	}
}


public class ExceptionDemo3 {
	public static void main(String[] args) {
		Demo2 d=new Demo2();
		
		
			int num=d.div(4,0);
			System.out.println("num="+num);
		
		  
			//处理这个对象，可以使用该对象的方法。
			//System.out.println("异常了");  //方法2：捕获异常
			//System.out.println(e.getMessage()); //异常信息
			//System.out.println(e.toString());   //异常名称+异常信息
			//e.printStackTrace();                //名字+信息+位置 jvm默认用这个处理方式
		
						
		System.out.println("over");

	}

}
